//! # D-Bus interface proxy for: `org.freedesktop.Notifications`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/Notifications' from service 'org.freedesktop.Notifications' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.Notifications",
    default_service = "org.freedesktop.Notifications",
    default_path = "/org/freedesktop/Notifications"
)]
pub trait Notifications {
    /// CloseNotification method
    fn close_notification(&self, id: u32) -> zbus::Result<()>;

    /// EmitActionInvoked method
    fn emit_action_invoked(&self, id: u32, action: &str) -> zbus::Result<()>;

    /// EmitResolved method
    fn emit_resolved(&self, id: u32, reason: i32) -> zbus::Result<()>;

    /// GetCapabilities method
    fn get_capabilities(&self) -> zbus::Result<Vec<String>>;

    /// GetNotificationJson method
    fn get_notification_json(&self, id: u32) -> zbus::Result<String>;

    /// GetServerInformation method
    fn get_server_information(&self) -> zbus::Result<(String, String, String, String)>;

    /// NotificationIds method
    fn notification_ids(&self) -> zbus::Result<Vec<u32>>;

    /// Notify method
    #[allow(clippy::too_many_arguments)]
    fn notify(
        &self,
        app_name: &str,
        replaces_id: u32,
        app_icon: &str,
        summary: &str,
        body: &str,
        actions: &[&str],
        hints: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
        expire_timeout: i32,
    ) -> zbus::Result<u32>;

    /// ActionInvoked signal
    #[zbus(signal)]
    fn action_invoked(&self, id: u32, action: &str) -> zbus::Result<()>;

    /// ActivationToken signal
    #[zbus(signal)]
    fn activation_token(&self, id: u32, token: &str) -> zbus::Result<()>;

    /// NotificationClosed signal
    #[zbus(signal)]
    fn notification_closed(&self, id: u32, reason: u32) -> zbus::Result<()>;

    /// Notified signal
    #[zbus(signal)]
    fn notified(&self, id: u32, replaced: bool) -> zbus::Result<()>;

    /// PropChanged signal
    #[zbus(signal)]
    fn prop_changed(&self, prop: &str) -> zbus::Result<()>;

    /// Resolved signal
    #[zbus(signal)]
    fn resolved(&self, id: u32, reason: i32) -> zbus::Result<()>;

    /// DontDisturb property
    #[zbus(property)]
    fn dont_disturb(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_dont_disturb(&self, value: bool) -> zbus::Result<()>;

    /// IgnoreTimeout property
    #[zbus(property)]
    fn ignore_timeout(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_ignore_timeout(&self, value: bool) -> zbus::Result<()>;
}
